/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:a6f47d9f-fc93-41bc-9cd7-a43177c5be30",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_hyA2t9bPF",
    "aws_user_pools_web_client_id": "1cfnearul0pqc2ghtsplmknj1v",
    "oauth": {}
};

export default awsmobile;
