/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:0e462e72-42d2-41c5-bbac-92f1e60436f9",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_FkXBHPx4f",
    "aws_user_pools_web_client_id": "31s2nrc55aap7kur16765ugsfs",
    "oauth": {}
};


export default awsmobile;
